### ISSUE TITLE
Index map import settings becoming incorrect

### ISSUE THREAD

**Issue by Zylann** [Zylann/godot_heightmap_plugin#170]
**Describe the bug**
When playing the game with a terrain using the array shader, the way texture boundaries "rainbow-blend" suggests interpolation is going on with the index map. That should not be the case, that texture must not have any filter.

**To Reproduce**
Unknown yet

**Expected behavior**
The index map must have no filter.

**Screenshots**
Visible in original report https://github.com/Zylann/godot_heightmap_plugin/issues/10#issuecomment-637898557

**Environment**
- OS: ?
- Graphics card: ?
- Godot version: 3.2.1
- Plugin version: 1.3

**Comment by tinmanjuggernaut** [comment]
Win10/64
GTX1060

**Comment by RonanZe** [comment]
I've open an issue about some kind of filter artefact I have here: #172 
But I'm starting to think it's the same problem that this one.

The filtering is different (with "U Depth Blending" switched off) between array.shader: 
![Capture86](https://user-images.githubusercontent.com/36386695/83928801-55373780-a791-11ea-908d-03f9fe9b9413.PNG)

 and simple4_lite.shader: 
![Capture87](https://user-images.githubusercontent.com/36386695/83928861-89125d00-a791-11ea-92e2-d94d717c51cd.PNG)

They should be the same?

**Comment by Zylann** [comment]
@RonanZe this is unrelated to the import settings highlighted by @tinmanjuggernaut . Also as explained in the doc, the textures used by the array shader are very different from the classic ones, so results are going to be different.

**Comment by Zylann** [comment]
@tinmanjuggernaut I had a look at my own test scene but I see my index map remained at proper settings. How did you reproduce that? The plugin does save an `.import` file with `flags/filter=false`, so there should be no way for that to magically change.

**Comment by Zylann** [comment]
Looks like there is a typo in map properties, I wrote `sgrb` everywhere instead of `srgb`...

**Comment by Zylann** [comment]
That should be fixed in 0d621678f494e533df3e313c7992304b102140e3

**Comment by tinmanjuggernaut** [comment]
I still have the issue. I don't see any difference, except now it is changing when I paint, whereas it wasn't before. Filter doesn't make any difference. I made a video for you. 
https://youtu.be/Q_hUDL3iZE0

**Comment by Zylann** [comment]
@tinmanjuggernaut the fix I made will not apply to *existing* terrains for which the bug happened. To test if it still happens you have to create a new terrain.
For existing terrains which had the issue, you'll have to edit import settings manually (textures inside the *terrain data* folder, not ground textures).
Also, I believe you should not change the `filter` or `mipmap` in the sub-inspectors either like you did in the video, because that's overriden by import settings, and these are fine already.

**Comment by tinmanjuggernaut** [comment]
By `index map`, you are referring to `splat_index.png`? That one file should have filter turned off, but it should be turned on for all of the terrain texture files that I create and import?

I recreated the terrain and so far the textures seem to be working properly and retaining updates.

**Comment by Zylann** [comment]
> By index map, you are referring to splat_index.png? 

Yes.

> That one file should have filter turned off, but it should be turned on for all of the terrain texture files that I create and import?

Technically the plugin is creating these, and writes a reverse-engineered `.import` file to prevent Godot from applying unfit default import settings (as there is no API to do that). Generally they all have filter, except the index map. Only a few have mipmaps as well and only color is srgb.
